// Regenerate catalog.json so the L1/L2 browser is grouped by each clip's own
// `taxonomy` field (industry -> Domain, scene -> Scenario) instead of the old
// COS-derived domain/scenario. The raw taxonomy strings are free-text and
// inconsistent, so they're folded through server/scripts/taxonomy-canon.json
// (the maintained canonical table) before grouping. Preview clip data
// (file/duration/hand/head/combo) is preserved verbatim — only the tree above
// it changes. Idempotent: re-run after adding clips or editing the canon table.
//
//   pnpm -C server gen:catalog      (or: pnpm gen:catalog from the repo root)

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

type Loc = { en: string; zh: string };
type Canon = { industry: Record<string, Loc>; scene: Record<string, Loc> };
type Clip = Record<string, unknown> & { file: string };

const ROOT = resolve(fileURLToPath(new URL("../../", import.meta.url)));
const CATALOG = resolve(ROOT, "catalog.json");
const CAPTIONS = process.env.CAPTIONS_DIR
  ? resolve(process.env.CAPTIONS_DIR)
  : resolve(ROOT, "captions");
const CANON = resolve(fileURLToPath(new URL("./taxonomy-canon.json", import.meta.url)));

const canon = JSON.parse(readFileSync(CANON, "utf8")) as Canon;

// Exact match, then trimmed / trailing-punctuation-stripped, then case-insensitive.
function lookup(map: Record<string, Loc>, raw: string): Loc | null {
  if (!raw) return null;
  const exact = map[raw];
  if (exact) return exact;
  const norm = raw.trim().replace(/[.\s]+$/, "").trim();
  const normed = map[norm];
  if (normed) return normed;
  const ciKey = Object.keys(map).find((k) => k.toLowerCase() === norm.toLowerCase());
  return (ciKey && map[ciKey]) || null;
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

const cat = JSON.parse(readFileSync(CATALOG, "utf8")) as { modalities: any[] };
const ego = cat.modalities.find((m) => m.id === "ego") ?? cat.modalities[0];
const others = cat.modalities.filter((m) => m !== ego);

// Flatten every preview clip currently under the ego modality.
const previews: Clip[] = [];
for (const d of ego.domains) for (const s of d.scenarios) previews.push(...s.previews);

const warnings: string[] = [];
type Scene = { loc: Loc; clips: Clip[] };
type Dom = { loc: Loc; scenes: Map<string, Scene> };
const tree = new Map<string, Dom>();

for (const clip of previews) {
  const capPath = resolve(CAPTIONS, clip.file.replace(/\.[^.]+$/, ".json"));
  let rawInd = "";
  let rawScn = "";
  if (existsSync(capPath)) {
    const tx = (JSON.parse(readFileSync(capPath, "utf8"))?.global?.taxonomy ?? {}) as Record<string, string>;
    rawInd = tx.industry_en ?? "";
    rawScn = tx.scene_en ?? "";
  } else {
    warnings.push(`no caption file for ${clip.file}`);
  }
  let ind = lookup(canon.industry, rawInd);
  let scn = lookup(canon.scene, rawScn);
  if (!ind) {
    warnings.push(`unmapped industry ${JSON.stringify(rawInd)} (${clip.file})`);
    ind = { en: rawInd || "Uncategorized", zh: rawInd || "未分类" };
  }
  if (!scn) {
    warnings.push(`unmapped scene ${JSON.stringify(rawScn)} (${clip.file})`);
    scn = { en: rawScn || "Other", zh: rawScn || "其他" };
  }
  if (!tree.has(ind.en)) tree.set(ind.en, { loc: ind, scenes: new Map() });
  const dom = tree.get(ind.en)!;
  if (!dom.scenes.has(scn.en)) dom.scenes.set(scn.en, { loc: scn, clips: [] });
  dom.scenes.get(scn.en)!.clips.push(clip);
}

const clipCount = (d: Dom) => [...d.scenes.values()].reduce((n, s) => n + s.clips.length, 0);

const domains = [...tree.values()]
  .sort((a, b) => clipCount(b) - clipCount(a) || a.loc.en.localeCompare(b.loc.en))
  .map((dom) => ({
    id: slug(dom.loc.en),
    name: dom.loc.en,
    nameZh: dom.loc.zh,
    scenarios: [...dom.scenes.values()]
      .sort((a, b) => b.clips.length - a.clips.length || a.loc.en.localeCompare(b.loc.en))
      .map((sc) => ({
        id: `${slug(dom.loc.en)}-${slug(sc.loc.en)}`,
        name: sc.loc.en,
        nameZh: sc.loc.zh,
        recordingCount: sc.clips.length,
        previews: sc.clips,
      })),
  }));

const out = {
  _comment:
    "Generated by server/scripts/gen-catalog-from-taxonomy.ts — L1/L2 grouped by each clip's taxonomy (industry/scene), folded through taxonomy-canon.json. Do not hand-edit; re-run `pnpm gen:catalog`.",
  modalities: [{ ...ego, domains }, ...others],
};
writeFileSync(CATALOG, JSON.stringify(out, null, 2) + "\n");

const nScen = domains.reduce((n, d) => n + d.scenarios.length, 0);
console.log(`wrote ${CATALOG}`);
console.log(`  ${domains.length} domains, ${nScen} scenarios, ${previews.length} previews`);
for (const d of domains) console.log(`  · ${d.name} (${d.scenarios.length}): ${d.scenarios.map((s) => `${s.name}×${s.recordingCount}`).join(", ")}`);
if (warnings.length) {
  console.log("\nWARNINGS — add these to taxonomy-canon.json and re-run:");
  for (const w of warnings) console.log("  - " + w);
} else {
  console.log("\nall taxonomy strings mapped cleanly.");
}
